ComplianceAuditWeb/Models/AboutCompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComplianceAuditWeb.Models
{
    public class AboutCompanyViewModel
    {
        public int CompanyID { get; set; }
        public string  CompanyName { get; set; }
        public string  CompanyNameG { get; set; }
        public string  GroupCompanyName { get; set; }
        public string CompanyDescription { get; set; }
        public string CompanyLogo { get; set; }
        public int ParentCompanyID { get; set; }
        public string Website { get; set; }
        public bool Is_Active { get; set; }
        public bool IsVendor { get; set; }

        public List<SelectListItem> CompaniesList { get; set; }
        public List<AboutCompanyViewModel> AboutGroupCompany { get; set; }
        public List<AboutCompanyViewModel> AboutCompany { get; set; }
        public List<AboutCompanyViewModel> AboutBranch { get; set; }
        public int CompanyListID { get; set; }
        public string CompanyNameList { get; set; }
        public int OrganizationID { get; set; }
        public string IndustryType { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string logo { get; set; }

    }

}

ComplianceAuditWeb/Models/BranchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Compliance.DataObject;
using System.Data;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ComplianceAuditWeb.Models
{
    public class BranchViewModel
    {
        public Organization organization { get; set; }
        public BranchLocation branch { get; set; }
        public string branchAuditingFrequency { get; set; }
     
        public List<SelectListItem> Country { get; set; }
        public List<SelectListItem> State { get; set; }
        public List<SelectListItem> City { get; set; }

        public List<SelectListItem> CompaniesList { get; set; }
        public string ChildCompanyName { get; set; }
        public List<SelectListItem> GroupCompaniesList { get; set; }
        [Required(ErrorMessage ="Please select the company")]
        public int CompanyID { get; set; }
        public int GroupCompanyID { get; set; }
        public string GroupCompanyName { get; set; }
        public List<SelectListItem> BranchList { get; set; }
        public int BranchID { get; set; }

        public List<SelectListItem> VendorList { get; set; }
        public int[] VendorID { get; set; }
        public int VendorsID { get; set; }
        public string VendorName { get; set; }
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public DateTime VendorStartDate { get; set; }
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public Nullable< DateTime> VendorEndDate { get; set; }
        public bool IsVendorActive { get; set; }

        public List<SelectListItem> ComplianceList { get; set; }
        public int[] ComplianceID { get; set; }
        //public int SingleComplianceID { get; set; }

       // public int[] currentID { get; set; }
        //public List<SelectListItem> currentList { get; set; }


        public int[] assignedID { get; set; }
        public List<SelectListItem> AssignedList { get; set; }

        public List<BranchViewModel> viewmodel { get; set; }
        public bool Is_Active { get; set; }
        public string Logo { get; set; }
        public string BranchName { get; set; }

    }
   
}

ComplianceAuditWeb/Models/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Compliance.DataObject;
using System.Data;
using System.Web.Mvc;

namespace ComplianceAuditWeb.Models
{
    public class CompanyViewModel
    {
        public Organization organization { get; set; }
        public BranchLocation branch { get; set; }
        public CompanyDetails companydetails { get; set; }
        public List<SelectListItem> Country { get; set; }
        public List<SelectListItem> State { get; set; }
        public List<SelectListItem> City { get; set; }

        public List<SelectListItem> GroupCompaniesList { get; set; }
        public int GroupCompanyID { get; set; }
        public string GroupCompanyName { get; set; }

        public List<SelectListItem> CompaniesList { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ChildCompanyName { get; set; }

        public List<SelectListItem> IndustryTypeList { get; set; }
       

        public List<SelectListItem> ComplianceList { get; set; }
        public int[] ComplianceID { get; set; }

        public AuditCalender AuditCalender { get; set; }

        public int yearid { get; set; }
        
        public IEnumerable<int> years { get; set; }

        public List<string> branchlist { get; set; }

    }
}

ComplianceAuditWeb/Models/ListofComplianceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Compliance.DataObject;

namespace ComplianceAuditWeb.Models
{
    public class ListofComplianceViewModel
    {
       public List<ComplianceXref> Actslist { get; set; }

       public List<SelectListItem> CountryList { get; set; }
       public  int countryid { get; set; }
        public List<SelectListItem> IndustryTypeList { get; set; }
        public int industrytypeid { get; set; }
        public List<SelectListItem> ComplianceTypeList { get; set; }
        public int compliancetypeid { get; set; }

        public List<ComplianceXref> Rulelist { get; set; }

        public ListofComplianceViewModel()
        {
            Actslist = new List<ComplianceXref>();
            CountryList = new List<SelectListItem>();
            IndustryTypeList = new List<SelectListItem>();
            ComplianceTypeList = new List<SelectListItem>();
            Rulelist = new List<ComplianceXref>();
        }
    }
}

ComplianceAuditWeb/Models/OrganizationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Compliance.DataObject;
using System.Data;
using System.Collections;
using System.Web.Mvc;

namespace ComplianceAuditWeb.Models
{
    public class OrganizationViewModel
    {
        public Organization organization { get; set; }
   

      

       

      


    }
    
}

ComplianceAuditWeb/Models/VendorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Compliance.DataObject;


namespace ComplianceAuditWeb.Models
{
    public class VendorViewModel
    {
        public Organization organization { get; set; }
        public CompanyDetails companydetails { get; set; }
        public BranchLocation location { get; set; }
        public List<SelectListItem> Country { get; set; }
        public List<SelectListItem> State { get; set; }
        public List<SelectListItem> City { get; set; }

        public List<SelectListItem> GroupCompaniesList { get; set; }
        public int GroupCompanyID { get; set; }
        public string GroupCompanyName { get; set; }

        public List<SelectListItem> CompaniesList { get; set; }
        [Required(ErrorMessage ="Please select the company")]

        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ChildCompanyName { get; set; }

        public List<SelectListItem> ComplianceList { get; set; }
        public int[] ComplianceID { get; set; }


        public List<SelectListItem> IndustryTypeList { get; set; }

        

      
    }
}

ComplianceAuditWeb/Controllers/ManageOrganizationController.cs
#region Code History
/*CODE HISTORY
 * ============================================================================================================
 *  Version No      DATE       Developer Name        Description
 * ===========================================================================================================
 *  1.0          28-06-2018    Mythri A        DataAccess Layer for UserPrivilege
 *                                                  The methods defined here are getRolePrivilege() and getPrivilege().
 *  
 */
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComplianceService;
using ComplianceAuditWeb.Models;
using Compliance.DataObject;
using System.Xml;
using System.Data;
using System.IO;
using System.Configuration;
using System.Web.UI.WebControls;
using System.Dynamic;

namespace ComplianceAuditWeb.Controllers
{
    public class ManageOrganizationController : Controller
    {
        // GET: ManageOrganization

        [HttpGet]
        public ActionResult AddGroupCompany()
        {
            OrganizationViewModel organizationVM = new OrganizationViewModel();
            try
            {
                organizationVM.organization = new Organization();
                organizationVM.organization.Organization_Id = 0;
            }
            catch (Exception ex)
            {
                return View("ErrorPage");
            }
            return View("_Organization", organizationVM);
        }

        [HttpPost]
        public ActionResult AddGroupCompany(OrganizationViewModel organizationVM, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        CommonController common = new CommonController();
                        organizationVM.organization.logo = Path.GetFileName(file.FileName);
                        string filePath = Path.Combine(Server.MapPath(ConfigurationManager.AppSettings["FilePath"].ToString()), Path.GetFileName(file.FileName));
                        string message = common.UploadFile(file, filePath);
                        ModelState.AddModelError("org_hier.logo", message);
                    }
                    else
                    {
                        CommonController common = new CommonController();
                        organizationVM.organization.logo = Path.GetFileName("noimage.png");
                        string filePath = Path.Combine(Server.MapPath(ConfigurationManager.AppSettings["FilePath"].ToString()), Path.GetFileName("noimage.png"));
                        string message = common.UploadFile(file, filePath);
                        ModelState.AddModelError("org_hier.logo", message);
                    }
                    OrgService.OrganizationServiceClient organizationClient = new OrgService.OrganizationServiceClient();
                    int GroupCompid = 0;
                    organizationVM.organization.User_Id = Convert.ToInt32(Session["UserID"]);
                    organizationVM.organization.Is_Leaf = false;
                    organizationVM.organization.Level = 1;
                    organizationVM.organization.Is_Active = true;
                    organizationVM.organization.Is_Delete = false;
                    organizationVM.organization.Is_Vendor = false;
                    organizationVM.organization.Parent_Company_Id = 0;
                    GroupCompid = organizationClient.insertOrganization(organizationVM.organization);
                    if (GroupCompid != 0)
                    {
                        TempData["ParentCompanyID"] = organizationVM.organization.Organization_Id;
                        string appkey = String.Join("", "group", GroupCompid);
                        string path = string.Join("/", ConfigurationManager.AppSettings["FilePath"], appkey);
                        Directory.CreateDirectory(Path.Combine(Server.MapPath(path)));
                        // ConfigurationManager.AppSettings[appkey] = path;
                        TempData["Success"] = "Group Company created successfully!!!";
                        return RedirectToAction("AboutGroupCompany", new { id = GroupCompid });
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Group Company creation was not successfull. Please try again!!!";
                    }
                }
                else
                {
                    ModelState.AddModelError("", ConfigurationManager.AppSettings["Requried"]);
                    organizationVM.organization.Organization_Id = 0;
                }
            }
            catch (Exception)
            {
                return View("ErrorPage");
            }
            return View("_Organization", organizationVM);
        }

        [HttpGet]
        public ActionResult UpdateGroupCompany(int OrgID)
        {
            OrganizationViewModel organizationViewModel = new OrganizationViewModel();
            try
            {
                OrgService.OrganizationServiceClient organizationClient = new OrgService.OrganizationServiceClient();
                string strxmlUpdatedData = organizationClient.getGroupOrganization(OrgID);
                DataSet dsUpdatedData = new DataSet();
                dsUpdatedData.ReadXml(new StringReader(strxmlUpdatedData));
                organizationViewModel.organization = new Organization();
                if (dsUpdatedData.Tables.Count > 0)
                {
                    organizationViewModel.organization.Organization_Id = OrgID;
                    organizationViewModel.organization.Organization_Id = Convert.ToInt32(dsUpdatedData.Tables[0].Rows[0]["Org_Hier_ID"]);
                    organizationViewModel.organization.Company_Name = dsUpdatedData.Tables[0].Rows[0]["Company_Name"].ToString();
                    organizationViewModel.organization.Description = dsUpdatedData.Tables[0].Rows[0]["Description"].ToString();
                    organizationViewModel.organization.Type = dsUpdatedData.Tables[0].Rows[0]["Type"].ToString();
                    organizationViewModel.organization.Is_Active = Convert.ToBoolean(Convert.ToInt32(dsUpdatedData.Tables[0].Rows[0]["Is_Active"]));
                    organizationViewModel.organization.Last_Updated_Date = Convert.ToDateTime(dsUpdatedData.Tables[0].Rows[0]["Last_Updated_Date"]);
                    organizationViewModel.organization.User_Id = Convert.ToInt32(dsUpdatedData.Tables[0].Rows[0]["User_ID"]);
                    organizationViewModel.organization.logo = dsUpdatedData.Tables[0].Rows[0]["logo"].ToString();
                    Session["Logo"] = organizationViewModel.organization.logo;
                }
            }
            catch (Exception)
            {
                return View("ErrorPage");
            }
            return View("_Organization", organizationViewModel);
        }

        [HttpPost]
        public ActionResult UpdateGroupCompany(OrganizationViewModel organizationVM, HttpPostedFileBase file)
        {
            try
            {
                organizationVM.organization.logo = Convert.ToString(Session["Logo"]);
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        CommonController common = new CommonController();
                        organizationVM.organization.logo = Path.GetFileName(file.FileName);
                        string filePath = Path.Combine(Server.MapPath(ConfigurationManager.AppSettings["FilePath"].ToString()), Path.GetFileName(file.FileName));
                        string message = common.UploadFile(file, filePath);
                        ModelState.AddModelError("org_hier.logo", message);
                    }
                    else
                    {
                        CommonController common = new CommonController();
                        organizationVM.organization.logo = Path.GetFileName("noimage.png");
                        string filePath = Path.Combine(Server.MapPath(ConfigurationManager.AppSettings["FilePath"].ToString()), Path.GetFileName("noimage.png"));
                        string message = common.UploadFile(file, filePath);
                        ModelState.AddModelError("org_hier.logo", message);
                    }
                    bool result = false;
                    OrgService.OrganizationServiceClient organizationClient = new OrgService.OrganizationServiceClient();
                    result = organizationClient.updateOrganization(organizationVM.organization);
                    if (result != false)
                    {
                        TempData["Success"] = "Updated successfully!!!";
                        return RedirectToAction("AboutGroupCompany", new { id = organizationVM.organization.Organization_Id });
                    }
                }
                ModelState.AddModelError("Company_Name", "Error occurred while updating");
            }
            catch (Exception)
            {
                return View("ErrorPage");
            }
            return RedirectToAction("UpdateGroupCompany", new { OrgID = organizationVM.organization.Organization_Id });
        }


        public ActionResult DeactivateGroupCompany(int Orgid)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool result = false;
                    OrgService.OrganizationServiceClient organizationServiceClient = new OrgService.OrganizationServiceClient();
                    OrgActivateDeactivateViewModel orgActivateDeactivateViewModel = new OrgActivateDeactivateViewModel();

                    string strxmlData = organizationServiceClient.getGroupOrganization(Orgid);
                    DataSet dsData = new DataSet();

ComplianceAuditWeb/Views/ManageOrganization/ErrorPage.cshtml
@{
    ViewBag.Title = "Error";
}
<ul class="breadcrumb ML15">
    <li><a href="">Error</a></li>
    <li> Error</li>
</ul>

<center>
    Internal error
</center>

ComplianceAuditWeb/Views/ManageOrganization/View.cshtml
@{
    ViewBag.Title = "Assign/Delete Vendors";
}
<ul class="breadcrumb ML15">
    <li><a href="">Dashboard</a></li>
    <li> Assigned Vendors</li>
</ul>
    <h2>Assigned Vendors</h2>
<center>
    @ViewBag.AMessage
</center>

<center>
    @ViewBag.MessageVendorName
    &nbsp;
    @ViewBag.MessageDeallocated
</center>

ComplianceAuditWeb/Views/ManageOrganization/_AboutBranch.cshtml
@model ComplianceAuditWeb.Models.AboutCompanyViewModel
@{
    ViewBag.Title = "About Branch";
}
<ul class="breadcrumb ML15">
    <li><a href="/ManageOrganization/SelectCompany">Branch Management</a></li>
    <li>About Branch</li>
</ul>
<h2 class="ML15">About Branch</h2>




@using (Html.BeginForm())
{

    <div>
        @if (Session["GroupCompanyName"] != null)
        {
            Model.GroupCompanyName = Session["GroupCompanyName"].ToString();

            <center>

                <h3 class="text-uppercase"> @Html.DisplayFor(m => m.GroupCompanyName)</h3>

                <h4 class="text-center">@Html.DisplayFor(m => m.CompanyNameList)</h4>

            </center>


        }
    </div>



    if (TempData["Success"] != null)
    {
        <center>
            <p id="successMessage">@TempData["Success"]</p>
        </center>
    }
    <div class="pull-right fa fa-pull-right" style="font-size:large">
        <i class="fa fa-plus"></i><font style="font-size:14px; color:dimgray; font-family:Arial">

            @Html.ActionLink("Create Branch", "AddBranch", new { Orgid = Model.ParentCompanyID })
        </font>
    </div>
    @*<img src="/UploadedFiles/@Model.CompanyLogo" alt="" />*@
    <div class="clearfix"></div>

    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("Branch Name")
            @Html.TextBoxFor(m => m.CompanyName, new { @class = "inputMaterial ui - autocomplete - input", @readonly = "readonly" })
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-xs-10 subSelect ">
        <div class="input-field">


            @Html.Label("Branch Description", new { @class = "floating-label" })
            @Html.TextAreaFor(m => m.CompanyDescription, new { @class = "inputMaterial ui - autocomplete - input", @rows = 10, @readonly = "readonly" })

        </div>
    </div>
    @*@Html.Label("Company Name", new { @class = "floating-label" })*@






    <div class="clearfix"></div>



    @Html.HiddenFor(m => m.CompanyID)
    @Html.HiddenFor(m => m.ParentCompanyID)

    <ul class="list-inline continueBtn">
        <li>


            <input type="submit" value="Cancel" class="btn primary-button" onclick="SelectGroupCompany"><span class="ripple" style="width: 92.6094px; height: 92.6094px; top: 49.5px; left: -19.1875px;"></span>

            @Html.ActionLink("Modify ", "UpdateBranch", new { Orgid = Model.CompanyID }, new { @class = "btn primary-button" })
            @Html.ActionLink("Delete", "DeleteBranch",  new{ Orgid = Model.CompanyID },
          new { @onclick = "return confirm('Are you sure you want to delete?');", @class = "btn primary-button" })
            @if (Model.Is_Active == true)
            {
                @Html.ActionLink("Deactivate", "DeactivateBranch",  new{ Orgid = Model.CompanyID },
          new { @onclick = "return confirm('Are you sure you want to deactivate?');", @class = "btn primary-button" })
            }
            else
            {
                @Html.ActionLink("Activate", "ActivateBranch",  new{ Orgid = Model.CompanyID },
          new { @onclick = "return confirm('Are you sure you want to activate?');", @class = "btn primary-button" })

            }


        </li>
    </ul>




    if (Model.AboutGroupCompany.Count > 0)
    {

        <div class="new_section_box">
            <div class="tab-content">
                <div id="home" class="tab-pane fade in active">
                    <h2 class="big_hdng" style="text-transform:none; border:0; margin-top:15px;">List of Vendors Assigned:</h2>


                    @foreach (var item in Model.AboutGroupCompany)
                    {
                        <div class="col-sm-3 QueList">
                            <div class="queContainer">
                                <a href="@Url.Action("AboutVendor", "ManageOrganization", new { id = item.OrganizationID })">
                                    @if (item.Is_Active == false)
                                    {
                                        <i class="fa fa-ban"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-check-circle"></i>
                                    }
                                    <span class="qIcon"><img src="/UploadedFiles/@item.CompanyLogo" alt="" style="height:60px;width:75px"></span>

                                    <h3 class="PB25"> @Html.DisplayFor(modelItem => item.CompanyNameList)</h3>
                                </a>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    }



                    <div class="clearfix"></div>

                </div>

            </div>

        </div>


    }
    else
    {
        <center>
            <p id="successMessage">@ViewBag.Message</p>
        </center>
    }
}

ComplianceAuditWeb/Views/ManageOrganization/_AboutVendor.cshtml
@model ComplianceAuditWeb.Models.AboutCompanyViewModel
@{
    ViewBag.Title = "About Vendor";
}

<ul class="breadcrumb ML15">
    <li><a href="/Common/dashboard?pid=9">Vendor Management</a></li>
    <li> About Vendor</li>
</ul>
<h2 class="ML15">About Vendor</h2>
<div class="mid_content_sec">
    @using (Html.BeginForm())
    {
        <div>
            @if (Session["GroupCompanyName"] != null)
            {
                Model.GroupCompanyName = Session["GroupCompanyName"].ToString();

                <center>

                    <h3 class="text-uppercase"> @Html.DisplayFor(m => m.GroupCompanyName)</h3>

                <h4 class="text-center">@Html.DisplayFor(m => m.CompanyNameList)</h4>

                </center>


            }
        </div>
        if (TempData["Success"] != null)
        {
            <center>
                <p id="successMessage">@TempData["Company"]@TempData["Success"]</p>
            </center>
        }
        <div class="pull-right fa fa-pull-right" style="font-size:large">
            <i class="fa fa-plus"></i><font style="font-size:14px; color:dimgray; font-family:Arial">
                @Html.ActionLink("Add Vendor", "AddVendor", new { Orgid = Model.ParentCompanyID })
            </font>
        </div>

        <div class="col-xs-4 subSelect ">
            <img src="/UploadedFiles/@Model.CompanyLogo" alt="" />
        </div>

        <div class="col-xs-8 subSelect ">
            <div class="input-field">
                @Html.Label("Vendor name")
                @Html.TextBoxFor(m => m.CompanyName, new { @class = "inputMaterial ui - autocomplete - input", @readonly = "readonly" })
            </div>
        </div>

        @*@Html.Label("Company Name", new { @class = "floating-label" })*@








        <div class="col-xs-8 subSelect ">
            <div class="input-field">


                @Html.Label("Vendor Description", new { @class = "floating-label" })
                @Html.TextAreaFor(m => m.CompanyDescription, new { @class = "inputMaterial ui - autocomplete - input", @rows = 10, @readonly = "readonly" })

            </div>
        </div>
        @Html.HiddenFor(m => m.CompanyID)
        @Html.HiddenFor(m => m.ParentCompanyID)
        <div class="clearfix"></div>
        <ul class="list-inline continueBtn">
            <li>
                @Html.ActionLink("Modify", "UpdateVendor", new { OrgID = Model.CompanyID }, new { @class = "btn primary-button" })

                <input type="submit" value="Cancel" onclick="SelectCompanyForVendor" class="btn primary-button">
                <span class="ripple" style="width: 92.6094px; height: 92.6094px; top: 49.5px; left: -19.1875px;"></span>
                @Html.ActionLink("Delete", "DeleteVendorUnderCompany",  new{ Orgid = Model.CompanyID },
         new { @onclick = "return confirm('Are you sure you want to delete?');", @class = "btn primary-button" })
                @if (Model.Is_Active == true)
                {
                    @Html.ActionLink("Deactivate", "DeactivateVendorUnderCompany",  new{ Orgid = Model.CompanyID },
        new { @onclick = "return confirm('Are you sure you want to deactivate?');", @class = "btn primary-button" })
                }
                else
                {
                    @Html.ActionLink("Activate", "ActivateVendorUnderCompany",  new{ Orgid = Model.CompanyID },
        new { @onclick = "return confirm('Are you sure you want to activate?');", @class = "btn primary-button" })

                }
                @*@Html.ActionLink("Assign/Dessign", "AssignDessignVendors", new { OrgID = Model.ParentCompanyID }, new { @class = "btn primary-button" })*@

            </li>
        </ul>




        if (Model.AboutGroupCompany.Count > 0)
        {

            <div class="new_section_box">
                <div class="tab-content">
                    <div id="home" class="tab-pane fade in active">
                        <h2 class="big_hdng" style="text-transform:none; border:0; margin-top:15px;">List of Branches Associated:</h2>


                        @foreach (var item in Model.AboutGroupCompany)
                        {
                            <div class="col-sm-3 QueList">
                                <div class="queContainer">
                                    <a href="@Url.Action("AboutBranch", "ManageOrganization", new { id = item.OrganizationID })">
                                        @if (item.Is_Active == false)
                                        {
                                            <i class="fa fa-ban"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-check-circle"></i>
                                        }
                                        <span class="qIcon"><img src="/UploadedFiles/@item.CompanyLogo" alt="" style="height:60px;width:75px"></span>
                                        <h3 class="PB25"> @Html.DisplayFor(modelItem => item.CompanyNameList)</h3>
                                    </a>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        }



                        <div class="clearfix"></div>

                    </div>

                </div>

            </div>


        }
        else
        {
            <center>
                <p id="successMessage">@ViewBag.Message</p>
            </center>
        }
    }


</div>

ComplianceAuditWeb/Views/ManageOrganization/_ClosureDate.cshtml
@model ComplianceAuditWeb.Models.CompanyViewModel
@using System.Configuration;
@{
    ViewBag.Title = "Audit Calender Closure Date";

}

@using (Html.BeginForm())
{
<div class="mid_content_sec">
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    @*<div class="col-xs-4 subSelect ">
            <div class="input-field">
                @Html.Label("Select Company", new { @class = "floating-label" })<span style="color:red">*</span>
                @Html.DropDownListFor(model => model.AuditCalender.CompanyID, Model.CompaniesList, new { @onchange = "javascript:GetComplianceType(this.value); ", @class = "inputMaterial ui - autocomplete - input" })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @if (Model.branchlist == null)
    {

        <div class="col-xs-4 subSelect ">
            <div class="input-field">
                @Html.Label("End Date", new { @class = "floating-label" })
                @Html.EditorFor(model => model.AuditCalender.EndDate, new { @class = "inputMaterial ui - autocomplete - input" })
                @Html.ValidationMessageFor(model => model.ComplianceID, "", new { @class = "text-danger" })
            </div>
        </div>
    }
    else
    {
        <div class="col-xs-4 subSelect ">
            <div class="input-field">
                @Html.Label("End Date", new { @class = "floating-label" })
                @Html.TextBoxFor(model => model.AuditCalender.EndDate, new { @readonly = "readonly", disabled = "disabled",
               @class = "inputMaterial ui - autocomplete - input" })
                @Html.ValidationMessageFor(model => model.ComplianceID, "", new { @class = "text-danger" })
            </div>
        </div>
   
            <p>Audit has not been closed for these branches</p>
            @foreach(var item in Model.branchlist)
            {
            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    @*@item.OrganizationID = @Session["BranchID"];*@
                    <a href="@Url.Action("", "ManageOrganization",new { id = Model.branch.Branch_Id })">

                        <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                     
                            <h3 class="PB25"> @Html.DisplayFor(modelItem => item)</h3>
                      
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>
            }
       
    }
</div>

}