ComplianceAuditWeb/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComplianceAuditWeb.Models;
using Compliance.DataObject;
using System.Xml;
using System.Data;
using System.IO;
using System.Configuration;

namespace ComplianceAuditWeb.Controllers
{
    public class UserManagementController : Controller
    {
       //GET:insertRoles
        [HttpGet]
        public ActionResult AddRoles()
        {
            RolesViewModel rolesView = new RolesViewModel();
            rolesView.roles = new Roles();
            rolesView.roles.RoleId = 0;
            UserService.UserServiceClient client = new UserService.UserServiceClient();
            string xmldata = client.GetPrivilege();
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            rolesView.Privilege = new List<SelectListItem>();
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {

                    rolesView.Privilege.Add(new SelectListItem() { Text = row["Privilege_Name"].ToString(), Value = row["Privilege_ID"].ToString() });
                }
            }
            return View("_AddRole", rolesView);
        }

        //Post:insertRoles
        [HttpPost]
        public ActionResult AddRoles(RolesViewModel rolesView)
        {
            if (ModelState.IsValid)
            {
                UserService.UserServiceClient client = new UserService.UserServiceClient();
                int roleid = client.insertRoles(rolesView.roles);
                client.insertRolePrivilege(roleid, rolesView.PrivilegeId);
                TempData["Message"] = "Created " + rolesView.roles.RoleName + " Succesfully.";
                return RedirectToAction("AddRoles");
            }
            else
                ModelState.AddModelError("", ConfigurationManager.AppSettings["Requried"]);
            return View("_AddRole", rolesView);
        }

        //Get:updateRoles
        [HttpGet]
        public ActionResult updateRoles(int Roleid)
        {
            RolesViewModel rolesView = new RolesViewModel();
            rolesView.roles = new Roles();
            rolesView.roles.RoleId = Roleid;
            UserService.UserServiceClient client = new UserService.UserServiceClient();
            DataSet dsrole = new DataSet();
            string xmldata=client.GetAllRoles(Roleid);
            dsrole.ReadXml(new StringReader(xmldata));
            rolesView.roles.RoleName = Convert.ToString(dsrole.Tables[0].Rows[0]["Role_Name"]);
            rolesView.roles.IsGroupRole = Convert.ToBoolean(Convert.ToInt32(dsrole.Tables[0].Rows[0]["Is_Group_Role"]));
            xmldata = client.GetPrivilege();
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            rolesView.Privilege = new List<SelectListItem>();
            dsrole = new DataSet();
            xmldata = client.getRolePrivilege(rolesView.roles.RoleId);
            dsrole.ReadXml(new StringReader(xmldata));
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    bool selected = false;
                    if (dsrole.Tables.Count > 0)
                    {
                        foreach (System.Data.DataRow roleid in dsrole.Tables[0].Rows)
                        {
                            if (Convert.ToInt32(roleid["Privilege_ID"]) == Convert.ToInt32(row["Privilege_ID"]))
                            {
                                selected = true;
                                break;
                            }
                        }
                    }
                    rolesView.Privilege.Add(new SelectListItem() { Text = row["Privilege_Name"].ToString(), Value = row["Privilege_ID"].ToString(), Selected = selected });
                }
            }
            return View("_AddRole", rolesView);
        }

        //Post:updateRoles
        [HttpPost]
        public ActionResult updateRoles(RolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserService.UserServiceClient client = new UserService.UserServiceClient();
                client.updateRoles(model.roles);
                client.DeleteRolePrivilege(model.roles.RoleId);
                client.insertRolePrivilege(model.roles.RoleId, model.PrivilegeId);
                return View("_AddRole", model);
            }
            else
                ModelState.AddModelError("", ConfigurationManager.AppSettings["Requried"]);
            return View("_AddRole", model);
        }

        //Get:AddUserGroup
        [HttpGet]
        public ActionResult AddUserGroup()
        {
            UserGroupViewModel GroupView = new UserGroupViewModel();
            GroupView.Group = new UserGroup();
            GroupView.Group.UserGroupId = 0;
            UserService.UserServiceClient Client = new UserService.UserServiceClient();          
            string xmldata = Client.GetRoles(1);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            GroupView.Roles = new List<SelectListItem>();
            GroupView.Roles.Add(new SelectListItem { Text = "--Select Roles--", Value = "0" });
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    GroupView.Roles.Add(new SelectListItem { Text = row["Role_Name"].ToString(), Value = row["Role_ID"].ToString() });
                }
            }
            ds = new DataSet();
            GroupView.Featurelist = new List<SelectListItem>();
            xmldata = Client.getmenu();
            ds.ReadXml(new StringReader(xmldata));
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    GroupView.Featurelist.Add(new SelectListItem { Text = row["Menu_Name"].ToString(), Value = row["Menu_ID"].ToString() });
                }
            }
            return View("_AddUserGroup", GroupView);
        }

        //Post:AddUserGroup
        [HttpPost]
        public ActionResult AddUserGroup(UserGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserService.UserServiceClient Client = new UserService.UserServiceClient();
                Client.insertGroups(model.Group);
                return View("CreateUser");
            }
            else
                ModelState.AddModelError("", ConfigurationManager.AppSettings["Requried"]);
            return View("_AddUserGroup", model);
        }

        //Get:Updateusergroup
        [HttpGet]
        public ActionResult Updateusergroup(int groupid)
        {
            UserService.UserServiceClient Client = new UserService.UserServiceClient();
            UserGroupViewModel model = new UserGroupViewModel();
            DataSet ds = new DataSet();
            string xmldata=Client.GetUserGroup(groupid);
            ds.ReadXml(new StringReader(xmldata));
            model.Group = new UserGroup();
            model.Group.UserGroupName = Convert.ToString(ds.Tables[0].Rows[0]["User_Group_Name"]);
            model.Group.UserGroupDescription = Convert.ToString(ds.Tables[0].Rows[0]["User_Group_Description"]);
            model.Group.UserRoleId = Convert.ToInt32(ds.Tables[0].Rows[0]["Role_ID"]);
            xmldata = Client.GetRoles(1);
            DataSet dsrole = new DataSet();
            dsrole.ReadXml(new StringReader(xmldata));
            model.Roles = new List<SelectListItem>();
            if (dsrole.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    model.Roles.Add(new SelectListItem { Text = row["Role_Name"].ToString(), Value = row["Role_ID"].ToString() });
                }
            }
            return View("_AddUserGroup", model);
        }

        //Post:Updateusergroup
        [HttpPost]
        public ActionResult Updateusergroup(UserGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserService.UserServiceClient Client = new UserService.UserServiceClient();
                Client.updateGroups(model.Group);
                return View("ListofUsergroup");
            }
            else
            ModelState.AddModelError("", ConfigurationManager.AppSettings["Requried"]);
            return View("_AddUserGroup", model);
        }

        //Get:AddUser
        [HttpGet]
        public ActionResult AddUser()
        {           
            UserViewModel userviewmodel = new UserViewModel();
            userviewmodel.User = new User();
            userviewmodel.User.UserId = 0;
            UserService.UserServiceClient Client = new UserService.UserServiceClient();                              
            string xmlGroups=Client.GetUserGroup(0);
            DataSet Groups = new DataSet();
            Groups.ReadXml(new StringReader(xmlGroups));
            userviewmodel.UserGroupList = new List<SelectListItem>();
            //userviewmodel.UserGroupList.Add(new SelectListItem { Text = "--Select--", Value = "0" });
            foreach (System.Data.DataRow row in Groups.Tables[0].Rows)
            {
                userviewmodel.UserGroupList.Add(new SelectListItem { Text = row["User_Group_Name"].ToString(), Value =row["User_Group_ID"].ToString() });
            }
            string xmlRoles=Client.GetRoles(0);
            DataSet dsRoles = new DataSet();
            dsRoles.ReadXml(new StringReader(xmlRoles));
            userviewmodel.RolesList= new List<SelectListItem>();

            //userviewmodel.RolesList.Add(new SelectListItem { Text = "--Select--", Value = "0" });
            //if (dsRoles.Tables.Count > 0)
            //{

ComplianceAuditWeb/Views/UserManagement/Landing_Page.cshtml
@{
    /**/

    ViewBag.Title = "Welcome Page";
}


<div class="mid_content_sec">

    <div class="col-xs-12 subSelect ">
        <div class="input-field">
            <p>
                <h2 class="ML15">Welcome</h2><h3>@Session["username"],<br /></h3><p><span style="margin-left:60%">Last Login Date : @Session["Last_Login"]</span></p>

                <img src="/UploadedFiles/@Session["photo"]" alt="" style="height:70px; width:70px; float:left" />

                @Session["emailid"],
            </p>
        </div>
        </div>


        </div>

ComplianceAuditWeb/Views/UserManagement/_AddRole.cshtml
@model ComplianceAuditWeb.Models.RolesViewModel

@{
    ViewBag.Title = "_Add RolePage";
}
<h2 class="ML15">Add Role</h2>
<ul class="breadcrumb ML15">
    <li><a href="/UserManagement/UserManagementdashboard">User Management</a></li>
    <li>Add Role</li>
</ul>
@using (Html.BeginForm())
{
<div class="mid_content_sec">
    @Html.AntiForgeryToken()
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("RoleName:", new { @class = "floating-label" })  <span style="color:red">*</span>
            @if (Model.roles.RoleId > 0)
            {@Html.DisplayFor(model => model.roles.RoleName)}
        else
        {
            @Html.TextBoxFor(model => model.roles.RoleName, new { @class = "inputMaterial ui-autocomplete-input", autocomplete = "off" })
            <span id="loading_data_icon"></span>
        }
        </div>
    </div>
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("IsGroupRole", new { @class = "floating-label" })
            @Html.CheckBoxFor(model => model.roles.IsGroupRole, new { @class = "inputMaterial ui-autocomplete-input", autocomplete = "off" })
            <span id="loading_data_icon"></span>

        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-xs-10 subSelect ">
        <div class="input-field">
            @if (Model.Privilege != null)
            {
                @Html.Label("Privilege", new { @class = "floating-label" })<span style="color:red">*</span>
                @Html.ListBoxFor(m => m.PrivilegeId, Model.Privilege, new { @class = "inputMaterialSelect ui - autocomplete - input ", autocomplete = "off" })
                <span id="loading_data_icon"></span>
            }
        </div>
    </div>
    <div class="clearfix"></div>
    <ul class="list-inline continueBtn">
        <li>
            @{string button = "save";}
            @if (Model.roles.RoleId > 0)
            {
                button = "Update";
                @Html.ActionLink("Delete", "Deleterole", routeValues: new { RoleId = Model.roles.RoleId, @class = "btn primary-button" })
            }
            <input type="submit" value=@button class="btn primary-button" />
            <input type="reset" value="Reset" class="btn primary-button" />
            <input type="button" value="Cancel" class="btn primary-button" />
            @*<button type="submit" class="btn primary-button" id="btnProceed" name="Button" value=@button onclick="return ShowHide()">Add Company<span class="ripple" style="width: 92.6094px; height: 92.6094px; top: 49.5px; left: -19.1875px;"></span></button>*@

        </li>
    </ul>
    @Html.Action("ListofRoles")
</div>
}

@*@Html.Action("","")*@

ComplianceAuditWeb/Views/UserManagement/_AddUser.cshtml
@model ComplianceAuditWeb.Models.UserViewModel
@using System.Configuration;
@{
    /**/

    ViewBag.Title = "Add User Page";
}
<ul class="breadcrumb ML15">
    <li><a href="/Common/dashboard">User Management</a></li>
    <li>Add User</li>
</ul>
<h2 class="ML15">Add User</h2>

@using (Html.BeginForm("AddUser", "UserManagement", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="mid_content_sec">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.User.UserId)

    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("FirstName", new { @class = "floating-label" })<span style="color:red">*</span>
            @Html.TextBoxFor(m => m.User.FirstName, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["FirstName"] })
            @Html.ValidationMessageFor(m => m.User.FirstName, "", new {@class = "help-block" })
        </div>
    </div>
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("MiddleName", new { @class = "floating-label" })<span style="color:red">&nbsp;</span>
            @Html.TextBoxFor(m => m.User.MiddleName, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["MiddleName"] })
        </div>
    </div>

    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("LastName", new { @class = "floating-label" })<span style="color:red">*</span>
            @Html.TextBoxFor(m => m.User.LastName, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["LastName"] })
            @Html.ValidationMessageFor(m => m.User.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("EmailId(UserName)", new { @class = "floating-label" })<span style="color:red">*</span>
            @if (Model.User.UserId <= 0)
            {
                @Html.TextBoxFor(m => m.User.EmailId, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["EmailId"] })
                <span id="loading_data_icon"></span>
                @Html.ValidationMessageFor(model => model.User.EmailId, "", new { @class = "text-danger" })
            }
            else
            {
                @Html.DisplayFor(m => m.User.EmailId, new { @class = "inputMaterial ui - autocomplete - input" })
                <span id="loading_data_icon"></span>
            }
        </div>
    </div>
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("Password", new { @class = "floating-label" })<span style="color:red">*</span>
            @Html.PasswordFor(m => m.User.UserPassword, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["Password"] })
            <span id="loading_data_icon"></span>
            @Html.ValidationMessageFor(m => m.User.UserPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("Confirm Password")<span style="color:red">*</span>
            @Html.PasswordFor(m => m.ConformPassword, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["Confirm_Password"] })
            @Html.ValidationMessageFor(m => m.ConformPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-xs-4 subSelect ">
        <div class="input-field">
            @Html.Label("Contact Number", new { @class = "floating-label" })<span style="color:red">*</span>
            @Html.TextBoxFor(m => m.User.ContactNumber, new { @class = "inputMaterial ui - autocomplete - input", placeholder = ConfigurationManager.AppSettings["Contact_Number"] })
            <span id="loading_data_icon"></span>
            @Html.ValidationMessageFor(m => m.ConformPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-xs-1 subSelect ">
        <div class="input-field">
            @Html.Label(ConfigurationManager.AppSettings["Gender"], new { @class = "floating-label" })<span style="color:red">*</span>
        </div>
    </div>
    <div class="col-xs-1 subSelect ">
        <div class="input-field">
            @Html.Label(ConfigurationManager.AppSettings["Male"], new { @class = "floating-label" })
            @Html.RadioButtonFor(m => m.User.Gender, "Male", new { @class = "inputMaterial ui - autocomplete - input " })
        </div>
    </div>
    <div class="col-xs-1 subSelect ">
        <div class="input-field">
            @Html.Label(ConfigurationManager.AppSettings["Female"], new { @class = "floating-label" })
            @Html.RadioButtonFor(m => m.User.Gender, "Female", new { @class = "inputMaterial ui - autocomplete - input " })
        </div>
    </div>
    @*<div class="col-xs-1 subSelect ">
            <div class="input-field">
                @Html.Label(ConfigurationManager.AppSettings["Others"], new { @class = "floating-label" })
                @Html.RadioButtonFor(m => m.User.Gender, "Others", new { @class = "inputMaterial ui - autocomplete - input " })
            </div>
        </div>*@
    <div class="col-xs-3 subSelect ">
        <div class="input-field">
            @if(Model.User.photo!=null)
            {
                <img src="/UploadedFiles/@Model.User.photo" alt="" />
            }
            <label for="file">Upload File:</label>
            <input type="file" name="file" id="file" />
            @Html.ValidationMessageFor(m=>m.User.photo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-xs-6 subSelect ">
        <div class="input-field">
            @Html.Label(ConfigurationManager.AppSettings["UserGroup"], new { @class = "floating-label" })
            @Html.ListBoxFor(m => m.UserGroupID, Model.UserGroupList, new { @class = "inputMaterialSelect ui - autocomplete - select ", size = "4", placeholder = ConfigurationManager.AppSettings["UserGroup"] })
            <span id="loading_data_icon"></span>
        </div>
    </div>
    @*<div class="col-xs-6 subSelect ">
        <div class="input-field">
            @Html.Label(ConfigurationManager.AppSettings["Roles"], new { @class = "floating-label" })
            @Html.ListBoxFor(m => m.RoleID, Model.RolesList, new { @class = "inputMaterialSelect ui - autocomplete - input ", size = "4", placeholder = ConfigurationManager.AppSettings["Roles"] })
            <span id="loading_data_icon"></span>
        </div>
    </div>*@
    <div class="clearfix"></div>

    <ul class="list-inline continueBtn">
        <li>
            @{string button = ConfigurationManager.AppSettings["Save"];}
            @if (Model.User.UserId > 0)
            {

                @*@Html.CheckBoxFor(m=>m.User.IsActive)*@
                button = ConfigurationManager.AppSettings["Update"];
                @Html.ActionLink(ConfigurationManager.AppSettings["Delete"], "DeleteUser", routeValues: new { UserId = Model.User.UserId }, htmlAttributes: new { @class = "btn btn-default" })
            }


            <button type="submit" class="btn primary-button" id="btnProceed" name="Button" value="Submit">@button<span class="ripple" style="width: 92.6094px; height: 92.6094px; top: 49.5px; left: -19.1875px;"></span></button>           
        </li>
        <li>
            <input type="reset" value="Reset" class="btn primary-button" />
        </li>
        <li>
            <input type="button" value="Cancel" class="btn primary-button" onclick="" />
        </li>
    </ul>
</div>
}

ComplianceAuditWeb/Views/UserManagement/_ListofRoles.cshtml
@model IEnumerable<ComplianceAuditWeb.Models.RolesViewModel>
@{ Layout = null;}
<div >
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>Role Name</th>
            <th>IsGroupRole</th>
            <th>Action</th>
            <th>Privilege</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(linkText: item.roles.RoleName, actionName: "updateRoles", routeValues: new { Roleid = item.roles.RoleId })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.roles.IsGroupRole)
                </td>
                <td>
                    @if (item.roles.IsActive)
                    {@Html.ActionLink("Deactive", "DeactivateRole", new { Roleid = item.roles.RoleId })}
                else
                { @Html.ActionLink("Deactive", "DeactivateRole", new { Roleid = item.roles.RoleId })}
                </td>
                <td>

                    @foreach (var row in item.Privilege)
                    {
                        @Html.DisplayFor(modelItem => row.Text)<br />
                    }
                </td>
            </tr>
        }
    </table>
</div>

ComplianceAuditWeb/Views/UserManagement/_ListofUsers.cshtml
@model IEnumerable<Compliance.DataObject.User>
@if (TempData["Message"] != null)
{
<p id="successMessage">
    @TempData["Message"]
</p>
}
<p style="text-align:right;margin-right:20px">
    <i class="fa fa-plus"></i>@Html.ActionLink("Add User", actionName: "AddUser")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model=>model.photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MiddleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.LastLogin)
        </th>
        <th>
            Action
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.CheckBox("chkdeactive")
                </td>*@
            <td>
                @{string source = "/UploadedFiles/" + item.photo;}
                <img src=@source alt="" height="50px" width="50px" />               
            </td>
            <td>
                @Html.ActionLink(linkText: item.FirstName, actionName: "UpdateUser", routeValues: new { UserId = item.UserId }, htmlAttributes: null)
            </td>
            <td>
                @Html.DisplayFor(modelitem => item.MiddleName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.LastLogin)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "UpdateUser", new { id=item.UserId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.UserId }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
            </td>
        </tr>
    }

</table>

@*<div class="new_section_box">
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <h2 class="big_hdng" style="text-transform:none; border:0; margin-top:15px;">User Management:</h2>
                @foreach (var item in Model)
                {
                    <div class="col-sm-3 QueList">
                        <div class="queContainer">

                            <a href="@Url.Action("UpdateUser","UserManagement", routeValues: new { UserId = item.UserId })">
                                <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                                <h3 class="PB25"> @Html.DisplayFor(modelItem => item.FirstName)</h3>
                                <h4 class="PB25">@Html.DisplayFor(modelitem => item.LastName)</h4>
                            </a>
                            <h4 class="PB25">@Html.DisplayFor(modelitem => item.EmailId)</h4>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                }
                <div class="clearfix"></div>

            </div>

        </div>

    </div>*@

ComplianceAuditWeb/Views/UserManagement/_UserManagementDashboard.cshtml
@{
    ViewBag.Title = "_UserManagementDashboard";
}

<div class="new_section_box">
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h2 class="big_hdng" style="text-transform:none; border:0; margin-top:15px;">User Management:</h2>

            <div class="col-sm-3 QueList">
                <div class="queContainer">       
                    <a href="@Url.Action("AddRoles","UserManagement")">
                        <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                        <h3 class="PB25">Add Roles</h3>
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <a href="@Url.Action("AddUserGroup","UserManagement")">
                        <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                        <h3 class="PB25">Add UserGroup</h3>
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <a href="@Url.Action("AddUser","UserManagement")"">
                        <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                        <h3 class="PB25">Add User</h3>
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <a href="@Url.Action("ListofUsers","UserManagement")"">
                        <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                        <h3 class="PB25">ListofUsers</h3>
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="clearfix"></div>

        </div>

    </div>

</div>