ComplianceAuditWeb/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ComplianceAuditWeb.Models
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.Password)]        
        public string UserPassword { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string EmailId { get; set; }
    }
}

ComplianceAuditWeb/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Compliance.DataObject;
using System.Data;
using System.IO;
using System.Configuration;
using ComplianceAuditWeb.Models;


namespace ComplianceAuditWeb.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common

        public JsonResult getstate(string countryid)
            {
            OrgService.OrganizationServiceClient organizationservice = new OrgService.OrganizationServiceClient();
            int ID = Convert.ToInt32(countryid);
            List<SelectListItem> state = new List<SelectListItem>();
            string strXMLStates = organizationservice.GetStateList(ID);
            DataSet dsstate = new DataSet();


            dsstate.ReadXml(new StringReader(strXMLStates));
            if (dsstate.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in dsstate.Tables[0].Rows)
                {                  
                    state.Add(new SelectListItem() { Text = row["State_Name"].ToString(), Value = row["State_ID"].ToString() });
                }
            }
            return Json(state, JsonRequestBehavior.AllowGet);
        }


        public JsonResult getcity(string stateid)
            {
            List<SelectListItem> cities = new List<SelectListItem>();
            int ID = Convert.ToInt32(stateid);
            OrgService.OrganizationServiceClient organizationservice = new OrgService.OrganizationServiceClient();
            string strXMLCities = organizationservice.GetCityList(ID);
            DataSet dsCities = new DataSet();
            dsCities.ReadXml(new StringReader(strXMLCities));
            if (dsCities.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in dsCities.Tables[0].Rows)
                {

                    cities.Add(new SelectListItem() { Text = row["City_Name"].ToString(), Value = row["City_ID"].ToString() });
                }
            }
            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getbranch(string compid)
        {
            List<SelectListItem> branch = new List<SelectListItem>();
            int ID = Convert.ToInt32(compid);
            AudService.AuditServiceClient auditServiceClient = new AudService.AuditServiceClient();
            string xmldata = auditServiceClient.getSpecificBranchList(ID);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            branch = new List<SelectListItem>();
            foreach (System.Data.DataRow row in ds.Tables[0].Rows)
            {
                branch.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
            }
            
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    branch.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
                }

            }
            return Json(branch, JsonRequestBehavior.AllowGet);
        }
       


        public JsonResult getcompany(string groupcompid)
        {
            List<SelectListItem> company = new List<SelectListItem>();
            int ID = Convert.ToInt32(groupcompid);
            OrgService.OrganizationServiceClient client = new OrgService.OrganizationServiceClient();
            string xmldata = client.GeSpecifictCompaniesList(ID);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            company = new List<SelectListItem>();
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    company.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
                }
            }
            Session["Company"] = company;
            return Json(company, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getcompanydropdown(string groupcompid)
        {
            List<SelectListItem> company = new List<SelectListItem>();
            int ID = Convert.ToInt32(groupcompid);
            OrgService.OrganizationServiceClient client = new OrgService.OrganizationServiceClient();
            string xmldata = client.getCompanyListDropDown(ID);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            company = new List<SelectListItem>();
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    company.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
                }
            }
            Session["Company"] = company;
            return Json(company, JsonRequestBehavior.AllowGet);
        }


        public JsonResult getspecificbranch(string compid)
        {
            List<SelectListItem> company = new List<SelectListItem>();
            int ID = Convert.ToInt32(compid);
            AudService.AuditServiceClient auditServiceClient = new AudService.AuditServiceClient();
            string xmldata = auditServiceClient.getSpecificBranchList(ID);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            company = new List<SelectListItem>();
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    company.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
                }
            }
            return Json(company, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getspecificbranchdropdown(string compid)
        {
            List<SelectListItem> company = new List<SelectListItem>();
            int ID = Convert.ToInt32(compid);
            OrgService.OrganizationServiceClient organizationServiceClient = new OrgService.OrganizationServiceClient();
            string xmldata = organizationServiceClient.getSpecificBranchListDropDown(ID);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            company = new List<SelectListItem>();
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    company.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
                }
            }
            return Json(company, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getspecificvendors(string compid,string branchid)
        {
            List<SelectListItem> vendors = new List<SelectListItem>();
            int ID = Convert.ToInt32(compid);
            int branchID = Convert.ToInt32(branchid);
            VendorService.VendorServiceClient vendorServiceClient = new VendorService.VendorServiceClient();
            OrgService.OrganizationServiceClient organizationServiceClient = new OrgService.OrganizationServiceClient();
            string xmldata = organizationServiceClient.getSpecificVendorListDropDown(ID, branchID);
            DataSet ds = new DataSet();
            ds.ReadXml(new StringReader(xmldata));
            vendors = new List<SelectListItem>();
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)
                {
                    vendors.Add(new SelectListItem { Text = Convert.ToString(row["Company_Name"]), Value = Convert.ToString(row["Org_Hier_ID"]) });
                }
            }
            return Json(vendors, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getdefaultcountry(string compid)
        {
            BranchViewModel branchVM = new BranchViewModel();
            int ID = Convert.ToInt32(compid);
            OrgService.OrganizationServiceClient organizationServiceClient = new OrgService.OrganizationServiceClient();
            string xmldata = organizationServiceClient.getDefaultCompanyDetails(ID);
            DataSet dsDefaultCompanyDetails = new DataSet();
            dsDefaultCompanyDetails.ReadXml(new StringReader(xmldata));
            branchVM.Country = new List<SelectListItem>();
            if (dsDefaultCompanyDetails.Tables.Count > 0)
            {                 
                branchVM.Country.Add(new SelectListItem() { Text = dsDefaultCompanyDetails.Tables[0].Rows[0]["Country_Name"].ToString(), Value = dsDefaultCompanyDetails.Tables[0].Rows[0]["Country_ID"].ToString() });
                branchVM.Country.Add(new SelectListItem() { Text = dsDefaultCompanyDetails.Tables[0].Rows[0]["State_Name"].ToString(), Value = dsDefaultCompanyDetails.Tables[0].Rows[0]["State_ID"].ToString() });
                branchVM.Country.Add(new SelectListItem() { Text = dsDefaultCompanyDetails.Tables[0].Rows[0]["City_Name"].ToString(), Value = dsDefaultCompanyDetails.Tables[0].Rows[0]["City_ID"].ToString() });
            }      
            return Json(branchVM.Country, JsonRequestBehavior.AllowGet);
        }


        public ActionResult dashboard(int pid)
        {
            List<Menus> menues = new List<Menus>();
            UserService.UserServiceClient client = new UserService.UserServiceClient();
            DataSet ds = new DataSet();
            string xmlmenu = client.getmenulist(Convert.ToInt32(Session["UserId"]), pid);
            ds.ReadXml(new StringReader(xmlmenu));
            if (ds.Tables.Count > 0)
            {
                foreach (System.Data.DataRow row in ds.Tables[0].Rows)

ComplianceAuditWeb/Views/Shared/Logout.cshtml
@{
    Layout = null;
    ViewBag.Title = "Logout Page";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="~/Content/assets/css/loginpage.css" rel="stylesheet" />
</head>
<body>
    <br />
    <br />
    <br />
    <div id="login">
        @using (Html.BeginForm())
        {

            <div style="align-content:center; margin-left:100px">
                <br />

                <img src="~/Content/assets/images/logo_new.png" /><br />
            </div>
            <hr/>
            <div style="text-align:center;">
                <h4>Successfully Logged out</h4>

                <p>
                    Click here to

                    @Html.ActionLink(linkText: "Login", actionName: "Login", controllerName: "UserManagement")
                    again.
                </p>
            </div>
    @*<input type="submit" value="Login">*@
    <br />
    <br />
    <br />
    }
    </div>
</body>
</html>

ComplianceAuditWeb/Views/Shared/_Dashboard.cshtml
@model IEnumerable < Compliance.DataObject.Menus>
@{ int listcount = 0;
    /* string path = String.Empty;*/
 }

<div class="new_section_box">
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h2 class="big_hdng" style="text-transform:none; border:0; margin-top:15px;"></h2>
            @foreach (var item in Model)
            {
                listcount++;
                <div class="col-sm-3 QueList">
                    <div class="queContainer">
                        @if (item.ParentMenuId == 0)
                        {
                            //path = string.Join(" ", item.PathUrl, "?pid=", item.Id);
                            string image="1"+item.icon;
                            <a href=@item.PathUrl?pid=@item.Id>
                                <span class="qIcon"><img src="/Content/assets/images/@image" alt="" />@*<i class="fa fa-users fa-5x"></i>*@</span>
                                <h3 class="PB25">@item.MenuName</h3>
                            </a>
                        }
                        else
                        {
                            //path = @item.PathUrl;

                        <a href=@item.PathUrl>
                            <span class="qIcon"><img src="/Content/assets/images/@item.icon" alt="" /></span>
                            <h3 class="PB25">@item.MenuName</h3>
                        </a>}
                    </div>
                </div>
                if (listcount == 4)
                {
                    <div class="clearfix"></div>
                }
            }
            @*<div class="col-sm-3 QueList">
            <div class="queContainer">
                <a href="@Url.Action("AddUserGroup","UserManagement")">
                    <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                    <h3 class="PB25">Add UserGroup</h3>
                </a>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="col-sm-3 QueList">
            <div class="queContainer">
                <a href="@Url.Action("AddUser","UserManagement")" ">
                    <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                    <h3 class="PB25">Add User</h3>
                </a>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="col-sm-3 QueList">
            <div class="queContainer">
                <a href="@Url.Action("ListofUsers","UserManagement")" ">
                    <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                    <h3 class="PB25">ListofUsers</h3>
                </a>
                <div class="clearfix"></div>
            </div>
        </div>*@

            <div class="clearfix"></div>

        </div>

    </div>

</div>

ComplianceAuditWeb/Views/Shared/_Footer.cshtml
@*@section footer
    {
    <div class="footer_text" style="padding-right:15px;">© 2018 paajakaconsulting.com All Rights Reserved</div>
    }*@

<div class="footer_text" style="padding-right:15px;">© 2018 paajakaconsulting.com All Rights Reserved</div> 

ComplianceAuditWeb/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/assets/css/loginpage.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <body>
        @Html.Action("Login", "UserManagement");
    </body>
</body>
</html>

ComplianceAuditWeb/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title </title>
    @Scripts.Render("~/bundles/jquery")


    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/assets/css/pagestyle.css" rel="stylesheet" />

    <script src="~/Content/assets/js/bootstrap.js"></script>
    <script src="~/Content/assets/js/jquery.min.js"></script>
    <script src="~/Content/bootstrap-3.3.7-dist/js/jquery.min.js"></script>
    <script src="~/Content/bootstrap-3.3.7-dist/js/jquery-ui.min.js"></script>
    <script src="~/Content/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    @*<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>*@
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />

</head>
<body>
    <div class="sidebar sidebar-collapsed">
        @Html.Action("MenuItems", "ManageAccess");
    </div>

    <div class="main_body pull-right none">
        <div class="dashboard">
            <div class="header">
                <div class="container-fluid">

                    <div class="row">
                        <div class="col-md-9">
                            <div class="col-md-9"><h1><img src="~/Content/assets/images/logo_new.png" /></h1></div>
                            <div class="col-md-3 pull-right"><h1 class="pull-right"><img src="" alt="" /></h1></div>
                        </div>
                        <div class="col-md-2">
                            <div style="margin:15px">
                                @if (Convert.ToInt32(Session["Isproductadmin"]) == 0)
                                {
                                    if (Session["GroupCompanyName"] != null)
                                    {
                                        <label>@Session["GroupCompanyName"]</label>
                                   
                                                <button id="GroupCompany" class="btn primary-button">Change</button>
                                             
                                                }
                                                else
                                                {
                                              
                                                        <button id="GroupCompany" class="btn primary-button">Select Group Company</button>
                                                
                                                        }
                                                        <div class="modal fade" id="bootstrapDialog" tabindex="-1" role="dialog" aria-labelledby="myModal-label" aria-hidden="true"
                                                             data-url='@Url.Action("SelectGroupCompany","Common")'>
                                                        </div>
                                                        }
</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="content-sec ML15">
            @RenderBody()
        </div>
        <div class="clearfix"></div>
    </div>
    <footer class="footer">
        @Html.Partial("~/Views/Shared/_Footer.cshtml")
    </footer>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>



    //
    <script>
        //$(function(){
        //    $('.queContainer').click(function(){
        //        $('.queContainer.active').addClass('active');
        //        $(this).toggleClass('active');
        //    });
        //});
        //</script>


    <script>

        $('.toggle').on('click', function () {
            $('.sidebar').toggleClass("sidebar-collapsed");
            $('.main_body').toggleClass("new_width");
        });
    </script>

    <script>
        //$(document).ready(function () {
        //    $('[data-toggle="popover"]').popover();
        //});
        $(document).ready(function () {
            $("[data-toggle='popover']").each(function () {
                $(this).popover({
                    title: $(this).data("valMsgFor"),
                    content: $(this).text()
                })
                    .html("<i class='glyphicon glyphicon-question-sign text-danger'></i>");
            }
            );
        });
    </script>
    <script>
        $(function () {
            $('.homeBtn').click(function () {
                $(this).toggleClass('active');
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('#GroupCompany').click(function () {
                var url = $('#bootstrapDialog').data('url');
                $.get(url, function (data) {
                    $('#bootstrapDialog').html(data);

                    $('#bootstrapDialog').modal('show');
                });
            });
        });
    </script>
    @*<style>
            body {
                overflow-y: hidden;
            }
        </style>*@
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

ComplianceAuditWeb/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width"/>
    <title>AddGroupCompany</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div>

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ComplianceAuditWeb/Views/Shared/_Login.cshtml
@model ComplianceAuditWeb.Models.LoginViewModel
@{ 
    Layout = null;
    ViewBag.Title = "Login Page";
 }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/assets/css/loginpage.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
        <br />
        <br />
        <br />

        <div id="login">
            @using (Html.BeginForm())
            {

                <div style="align-content:center; margin-left:100px">
                    <br />

                    <img src="~/Content/assets/images/logo_new.png" /><br /><br /><br />
                </div>

                <span class="fontawesome-user"></span>
                @Html.TextBoxFor(model =>model.EmailId, new { id = "user", placeholder = "Username" })


                <span class="fontawesome-lock"></span>
                @Html.PasswordFor(model => model.UserPassword, new { id = "pass", placeholder = "Password" })


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <input type="submit" value="Login">
                <br />
                <br />
                <p class="message">Forgot Password? <a href="#">Click Here</a></p>
                <br />
            }
        </div>
    </body>
</html>

ComplianceAuditWeb/Views/Shared/_Menu.cshtml
@model List<Compliance.DataObject.Menus>
<div class="toggle">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</div>
<div class="left_panel">
    <div class="top_panel">
        <h3>
            @if (Session["username"] != null)
            {
                @Session["username"].ToString()<br />
                <span>@Session["emailid"].ToString()</span>
            }
        </h3>
        <p><a href="/UserManagement/Logout">Logout</a></p>
    </div>
    <ul>
        @foreach (var menu in Model)
        {
            <li><a href="@menu.PathUrl?pid=@menu.Id" data-toggle="tooltip" title="@menu.MenuName">@menu.MenuName <span class="iconnew"><img style="width:30px;height:30px" src="~/Content/assets/images/@menu.icon" alt="" />@*<i class="fa fa-users fa-2x"></i></span>*@</a></li>
        }
    </ul>

    @*@foreach (var menu in Model)
    {
        if (menu.ParentMenuId == 0)
        {
            <ul>
                <li><a href="@menu.PathUrl">@menu.MenuName <span class="iconnew"><i class=""><img src="~/Content/assets/images/@menu.icon" alt="" /></i></span></a></li>
                @foreach (var item in Model)
                {
                    if (item.ParentMenuId == menu.Id)
                    {
                    <li><a href="@item.PathUrl">@item.MenuName <span class="iconnew"><i class=""><img src="~/Content/assets/images/@item.icon" alt="" /></i></span></a></li>
                        }
                 }
            </ul>
            }
        }*@
    </div>

ComplianceAuditWeb/Views/Shared/_SelectGroupCompany.cshtml
@model IEnumerable<SelectListItem>

@{
    ViewBag.Title = "Select Group Company";
    Layout = null;
}
<head>
    <script>
        $(function() {
            $('#btnsave').click(function () {
                var _id = $("#GroupDropdown").val();
                $.ajax({
                    type: "POST",
                    url: "/Common/SelectGroupCompany",
                    data: { GroupDropdown: _id },
                    success: function (data) {
                        if (data.success) {
                            $('#bootstrapDialog').modal('hide');
                            location.href = location.href;                        
                        }
                        else {
                            $('#bootstrapDialog').html(data.message);
                        }
                    },
                    error: function () {
                        alert("Error");
                    }
                });
            });
        });
    </script>
</head>
@*@using (Html.BeginForm("SelectGroupCompany","Common",FormMethod.Post))
{*@
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModal-label">Select Group Company</h4>
            </div>
            <div class="modal-body">
                @Html.DropDownList("GroupDropdown", Model, null, new { @class = "inputMaterial ui - autocomplete - input" })
                <input type="hidden" id="GroupDropdown" />
                <br />
                @*<input type="submit" value="select" class="btn primary-button" onclick="assigngroupCompany()" />*@
            </div>
            <div class="modal-footer">
                <button class="btn primary-button" id="btnsave">Select</button>
                <button class="btn primary-button" data-dismiss="modal" id="btnCancel">Cancel</button>
            </div>
        </div>      
    </div>
@*}*@

ComplianceAuditWeb/Views/Shared/_sampleDashboard.cshtml
@{
    ViewBag.Title = "_sampleDashboard";
}

<div class="new_section_box">
    <div class="tab-content">

        <div id="home" class="tab-pane fade in active">


            <h2 class="big_hdng" style="text-transform:none; border:0; margin-top:15px;">Manage Company:</h2>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                    <h3 class="PB25">Company 1</h3>
                    <div class="clearfix"></div>


                </div>
            </div>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <span class="qIcon"><img src="images/company1.JPG" alt=""></span>
                    <h3 class="PB25">Company 2</h3>
                    <div class="clearfix"></div>


                </div>
            </div>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <span class="qIcon"><img src="images/company1.JPG" alt=""></span>
                    <h3 class="PB25">Company 1</h3>
                    <div class="clearfix"></div>


                </div>
            </div>

            <div class="col-sm-3 QueList">
                <div class="queContainer">
                    <span class="qIcon"><img src="images/company2.JPG" alt=""></span>
                    <h3 class="PB25">Company 2</h3>
                    <div class="clearfix"></div>


                </div>
            </div>

            <div class="clearfix"></div>

        </div>

    </div>

</div>